version: 2
jobs:
  build:
    docker:
      - image: circleci/node:lts
    branches:
      only:
        - master
        - ci
    environment:
      NODE_OPTIONS: "--max-old-space-size=4096"
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          - v1-dependencies-
      - run: npm ci
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run: |
          set -o errexit
          set -o pipefail
          set -o nounset

          STATUS=0

          npm run tslint -- --format junit --out "junit/tslint.xml" || STATUS=1
          npm run test -- --no-cache --reporters=jest-junit --reporters=default || STATUS=1

          exit $STATUS
      - store_test_results:
          path: junit/
      - store_artifacts:
          path: junit/
