version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10-browsers
    branches:
      only:
        - master
        - ci
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm run-script test-junit
      - store_test_results:
          path: junit/
      - store_artifacts:
          path: junit/
